### ISSUE TITLE
Step Tracker

### ISSUE THREAD

**Issue by mrkrumhausen** [telus/tds-core#211]
**Description**
Leverage current design from Hydra
Step tracker to support max 6 steps.

**Designs**

Staging:
https://www.wcstage.telus.com/my-account/easy-roam?country=USA&ban=hXtWsVUMwVkjau38FesNVA&sub=yR61DxoBdDQoQCCTX-9omg
Login with vanessabailey@telusinternal.com / P4ssw0rd_]

**Design Acceptance Criteria**
- [ ] Add component to Sketch file and TDS Zeplin board. Include all variations and state
- [ ] Design meets TDS accessibility guidelines
- [ ] Design validated by dev
- [ ] Finalize design documentation
